version: "3.9"

services:
  db:
    image: postgres:14.9
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    container_name: pagoplux
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
